# Generated by Django 4.2.7 on 2023-11-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempts',
            old_name='assessment_id',
            new_name='assessment',
        ),
    ]
